services:
  opensearch-init:
    image: ${BACKEND_IMAGE:-openimis-backend}
    env_file:
      - .env.openSearch
    depends_on:
      - db
      - backend
      - opensearch
      - opensearch-dashboards
    command: >
      sh -c "
        echo 'Running dashboard configuration upload...' &&
        python manage.py upload_opensearch_dashboards --host-domain http://backend:8000 --imis-password ${OPENIMIS_ADMIN_PASS}
      "
    networks:
      - openimis-net
